### PR TITLE
Fix public file check in lib.php

### PR DESCRIPTION
**Pull request by cameron1729**
The check in lib.php was using the contenthash of the (potentially) resized file, which would never be in the cache of public files. This patch changes it so it uses the canonical hash when checking if the file is public.

### CODE REVIEW

**Comment by brendanheywood** [comment]
@gthomas2 I'm happy with this. You gave me permissions to merge on this repo a while back, are you happy if I merge things like this in or would you like me to always give you the final approval step?

**Review by gthomas2 — APPROVED** [review]

**Comment by gthomas2** [comment]
@brendanheywood - we should try for 2 reviewers if possible within a 24 hour window. After 24 hours if it's something that needs fixing fast then I'm happy for you to merge. I'll file pull requests myself in future so that you can review them.

**Comment by gthomas2** [comment]
@cameron1729 - Thank you for your latest PR. Merged.

**Comment by brendanheywood** [comment]
thanks @gthomas2

**Pull request merged**
